import React, { Component } from "react";
import "../../../allcss.css";
import Search from "../../../assets/Body/Guide/search.svg";
import Select from "../../../assets/Body/Guide/select.svg";
import Stand from "../../../assets/Body/Guide/stand.png";
import Guidecompo from "./Guidecompo";

class Guide extends Component{
  render() { 
    return (
    <div className="Guide-wrapper">
      <Guidecompo imgsrc={Search} title="Search" para="Simply add a keyword or a term related to your business in the
            slogan maker search box. Wait for the magic to happen."
            />
      <Guidecompo imgsrc={Select} title="Select" para="Choose from thousands of options generated by the slogan maker that fit your needs."
            />
      <Guidecompo imgsrc={Stand} title="Stand Out" para="Congrats on your new slogan. It's time to win the world!"
            />
    </div>
    );
}
};

export default Guide;
